### ISSUE TITLE
cant download the models form https://cmu.box.com/？

### ISSUE THREAD

**Issue by luyitry** [castacks/tartanvo#1]
Try to use VPN and other ways to download, but there is no way to open the web page to obtain the relevant files successfully. Could you upload the files to Baidu cloud disk or Google cloud disk，plz？Thx.

**Comment by Amigoshan** [comment]
We also provide links from Azure cloud: https://github.com/castacks/tartanvo#alternative-download-links
I just added two new download options from Baidu cloud and Google drive.

**Comment by Amigoshan** [comment]
We also provide links from [Azure cloud](https://github.com/castacks/tartanvo#alternative-download-links). 
I just added two new download options from Baidu cloud and Google drive. Please try those out!
Baidu cloud: https://pan.baidu.com/s/1votDi0zbDXOKK4-4gtgczQ   Code: vbtb 
Google drive: https://drive.google.com/drive/folders/1kzj2ZR4AxnDyR8elFhfnS2yX1wIxQaZO?usp=sharing

**Comment by luyitry** [comment]
> We also provide links from [Azure cloud](https://github.com/castacks/tartanvo#alternative-download-links).
> I just added two new download options from Baidu cloud and Google drive. Please try those out!
> Baidu cloud: https://pan.baidu.com/s/1votDi0zbDXOKK4-4gtgczQ Code: vbtb
> Google drive: https://drive.google.com/drive/folders/1kzj2ZR4AxnDyR8elFhfnS2yX1wIxQaZO?usp=sharing

Got it! Thank you very much!
